server:
  port: 8081
  servlet:
    encoding:
      charset: utf-8
      enabled: true
    multipart:
      enabled: 'true'
      location: volumes/ming/git/learnfromcode:\upload
      max-request-size: 30MB
      max-file-size: 10MB

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/book
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Roon1379@@

jpa:
  hibernate:
  ddl-auto: create #create,update.none
  naming:
  physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

com:
    example:
      upload: path =/Volumes/ming/git/LearnFromCode\upload