server:
  port: 8081
  servlet:
    encoding:
      charset: utf-8
      enabled: true


spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/book
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Roon1379@@

jpa:
  hibernate:
  ddl-auto: update #create,update.none
  naming:
  physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
